name: terraform workflows

on:
  push:
    branches:
      - feature/**
      - hotfix/**

  pull_request:
    branches:
      - dev
      - master
      - main

  workflow_dispatch:

jobs:
  Release:
    if: ${{ github.event_name == 'pull_request' }}
    uses: cumberland-cloud/workflows/.github/workflows/tf-release.yml@main
    secrets: inherit
      # NOTE: Uncomment this line if your workflow requires secret Terraform variables! 
      #         See documentation /docs/source/TERRAFORM.md for more info.
      # TF_ENV: ${{ secrets.TF_ENV }}
    with: 
      TF_STATE_KEY: gateway/terraform.tfstate
      TF_DEPLOY: true
      
  Scan:
    if: ${{ github.event_name == 'push' }}
    uses: chinchalinchin/github-workflows/.github/workflows/tf-scan.yaml@main

  Lint:
    if: ${{ github.event_name == 'push' }}
    uses: chinchalinchin/github-workflows/.github/workflows/tf-lint.yaml@main

  Docs:
    if: ${{ github.event_name == 'pull_request' }}
    uses: chinchalinchin/github-workflows/.github/workflows/gh-pages.yaml@main
