# Workflow to generate website resources using Sphinx Material and commit them to the gh-pages branch of a repository. 
# Requirements:
#   1.The gh-pages branch must be initialized prior to using this workflow. 
#   2. The Sphinx project must be nested in a /docs/ directory. 
# This workflow can also be configured to work with tfdocs by passing in an input variable. If using this feature, there is an additional requirement:
#   3. your repository must contain a .terraform-docs.yml configuration file in the project's root directory.

name: github pages

# see: https://docs.github.com/en/actions/using-workflows/reusing-workflows#overview
on: 
  workflow_call:
    # see: https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow
    inputs:
      DOCS_DIR:
        required: false
        description: Directory where docs are kept
        default: docs
        type: string
      NO_CACHE:
        required: false
        description: Flag to turn off dependency caching.
        default: false 
        type: boolean 
      LATEX:
        required: false
        description: Flag to turn install LaTeX (if Sphinx needs it)
        default: false
        type: boolean
      PYTHON_MATHLIBS:
        required: false
        description: Flag to install Python libraries for rendering mathematics.
        default: false
        type: boolean
      TF_DOCS:
        required: false
        description: Flag to run tf-docs before sphinx to generate markdown. Note, it is assumed the .terraform-docs.yml is configured to output markdown into the Sphinx /source/ directory and that no further configuration is required.
        default: false
        type: boolean
      ACTIONS_BOT_USERNAME:
        required: false
        description: Username of the bot that will push commits back to the gh-pages branch of the repository.
        default: github-slave-bot
        type: string
      ACTIONS_BOT_EMAIL:
        required: false
        description: Email of the bot that will push commits back to the gh-pages branch of the repository.
        default: slave@github.com
        type: string

jobs:
  # TODO: allow user to specify which theme and version to use.
  sphinx_gh_pages:
    name: github pages
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ inputs.ACTIONS_BOT_USERNAME }}
      EMAIL: ${{ inputs.ACTIONS_BOT_EMAIL }}
      DOCS_DIR: ${{ inputs.DOCS_DIR }}
      TFDOCS_VERSION: 0.16.0
      SPHINX_VERSION: 5.0.0
      BOOK_VERSION: 1.0.1
      GROUNDWORK_VERSION: 1.1.1
      MATERIAL_VERSION: 0.0.35
      TOOLBOX_VERSION: 3.5.0
      MATPLOTLIB_VERSION: 3.7.2
      MPLBACKEND: Agg

    steps:
      # see: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: environment
        run: echo "PATH=${GITHUB_WORKSPACE}/bin:$PATH" >> $GITHUB_ENV

      # TODO: how to cache system dependencies?
      # see: https://github.com/cli/cli/issues/6175#issuecomment-1238477714
      - name: system dependencies
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg |\
            sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
            && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
            && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" |\
              sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null

          sudo apt-get update -y 
          sudo apt-get install -y \
            python3-dev \
            python3-venv \
            python3-pip \
            build-essential

      - name: latex dependency
        if: inputs.LATEX
        run: |
          sudo apt update -y 
          # sudo apt upgrade -y 
          sudo apt install texlive-latex-extra -y
          sudo apt-get install -y dvipng

      - name: python math dependency
        if: inputs.PYTHON_MATHLIBS
        run: |
          sudo apt-get install -y python3-tk

      # see: https://github.com/actions/checkout
      - name: checkout
        uses: actions/checkout@v3

      # see: https://github.com/actions/cache
      - name: tfdocs cache
        if: inputs.TF_DOCS && !inputs.NO_CACHE
        id: cache_tfdocs
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/bin
          key: ${{ github.repository }}-${{ env.TFDOCS_VERSION }}-tfdocs

      - name: sphinx cache
        id: cache_sphinx
        if: ${{ !inputs.NO_CACHE }}
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/venv
          key: ${{ github.repository }}-${{ env.SPHINX_VERSION }}-sphinx-venv

      - name: doc dependencies
        if: steps.cache_sphinx.outputs.cache-hit != 'true' || !inputs.NO_CACHE
        run: |
          python3 -m venv ${GITHUB_WORKSPACE}/venv
          source ${GITHUB_WORKSPACE}/venv/bin/activate
          pip3 install sphinx==${SPHINX_VERSION} \
                        sphinx-material==${MATERIAL_VERSION} \
                        myst-parser \
                        groundwork-sphinx-theme==${GROUNDWORK_VERSION} \
                        sphinx-book-theme==${BOOK_VERSION} \
                        sphinx-toolbox==${TOOLBOX_VERSION}

      - name: doc math dependencies
        if: steps.cache_sphinx.outputs.cache-hit != 'true' || !inputs.NO_CACHE && inputs.PYTHON_MATHLIBS 
        run: |
          source ${GITHUB_WORKSPACE}/venv/bin/activate
          pip3 install matplotlib==${MATPLOTLIB_VERSION}

      - name: job dependencies
        if: steps.cache_tfdocs.outputs.cache-hit != 'true' && inputs.TF_DOCS || !inputs.NO_CACHE
        run: |
          curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v${TFDOCS_VERSION}/terraform-docs-v${TFDOCS_VERSION}-$(uname)-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          if [ ! -d "${GITHUB_WORKSPACE}/bin" ]; then
            mkdir ${GITHUB_WORKSPACE}/bin
          fi
          mv terraform-docs ${GITHUB_WORKSPACE}/bin

      # see: https://terraform-docs.io/user-guide/configuration/
      - name: build docs
        if: inputs.TF_DOCS
        run: |
          if [ -f ".tfdocs.yaml" ]
          then
            terraform-docs --config .tfdocs.yaml .
          fi

      # see: https://www.sphinx-doc.org/en/master/
      - name: build html
        run: |
          source ${GITHUB_WORKSPACE}/venv/bin/activate
          cd ${DOCS_DIR}
          make html
          cd ..
          
      - name: copy html to tmp
        run: |
          mkdir $(pwd)/../tmp
          cp -ap ./${DOCS_DIR}/build/html/. $(pwd)/../tmp/

      # note: disjunction of command with true to avoid possible failures
      - name: commit
        run: |
          git config --global user.name $USERNAME
          git config --global user.email $EMAIL
          git add .
          git stash
          git fetch
          git checkout gh-pages
          cp -ap $(pwd)/../tmp/. ./
          git add .
          git commit -m "$(echo $(date)) Auto-Documentation Bot: Beep Boop" || true
          git push --set-upstream origin gh-pages || true