name: Python Lint


# TODO


# see: https://docs.github.com/en/actions/using-workflows/reusing-workflows#overview
on: 
  workflow_call:
    inputs: 
      SRC_DIR:
        description: Path, relative to the repository root directory, where the source code is located.
        required: false
        type: string
        default: .

jobs:
  tflint:
    name: terraform lint
    runs-on: ubuntu-latest
    env:
      PYLINT_VERSION: 2.17.5
      SRC_DIR: ${{ inputs.SRC_DIR }}

    steps:
      # see: 
        # GITHUB_ENV: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: environment
        run: |
          echo "PATH=$(pwd)/bin:$PATH" >> $GITHUB_ENV

      # see: https://github.com/actions/checkout
      - name: checkout
        uses: actions/checkout@v3

      # see: https://github.com/actions/cache
      - name: pylint cache
        id: cache_pylint
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/venv
          key: ${{ github.repository }}-${{ env.PYLINT_VERSION }}-pylint
      
      - name: dependencies
        if: steps.cache_pylint.outputs.cache-hit != 'true'
        run: |
          python3 -m venv ${GITHUB_WORKSPACE}/venv
          source ${GITHUB_WORKSPACE}/venv/bin/activate
          pip3 install pylint==${PYLINT_VERSION}

      - name: plugins
        if: steps.cache_plugins.outputs.cache-hit != 'true'
        run: |
          cd ${SRC_DIR}
          pylint --rc-file .pylint.rc