name: Terraform Lint

# see: https://docs.github.com/en/actions/using-workflows/reusing-workflows#overview
on: workflow_call

jobs:
  tflint:
    name: terraform lint
    runs-on: ubuntu-latest
    env:
      TFLINT_VERSION: v0.47.0

    steps:
      # see: 
        # GITHUB_ENV: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
        # TFLINT_INSTALL_PATH: https://github.com/terraform-linters/tflint/blob/b899b18a6be5e8aff7b224dad62fb772b8a5fa0f/install_linux.sh#L68
        # TFLINT_PLUGIN_DIR: https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md
      - name: environment
        run: |
          echo "PATH=${GITHUB_WORKSPACE}/bin:$PATH" >> $GITHUB_ENV
          echo "TFLINT_INSTALL_PATH=${GITHUB_WORKSPACE}/bin" >> $GITHUB_ENV
          echo "TFLINT_PLUGIN_DIR=${GITHUB_WORKSPACE}/plugins" >> $GITHUB_ENV

      # see: https://github.com/actions/checkout
      - name: checkout
        uses: actions/checkout@v3

      # see: https://github.com/actions/cache
      - name: tflint cache
        id: cache_tflint
        uses: actions/cache@v3
        with:
          path: ${{ env.GITHUB_WORKSPACE }}/bin
          key: ${{ github.repository }}-${{ env.TFLINT_VERSION }}-tflint
      
      - name: plugin cache
        id: cache_tflint_plugins
        uses: actions/cache@v3
        with:
          path: ${{ env.GITHUB_WORKSPACE }}/plugins
          key: ${{ github.repository }}-${{ hashFiles('.tflint.hcl')}}-tflint-plugins

      - name: dependencies
        if: steps.cache_tflint_plugins.outputs.cache-hit != 'true'
        run: |
          if [ ! -d "${GITHUB_WORKSPACE}/bin" ]; then
            mkdir bin
          fi
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: plugins
        if: steps.cache_plugins.outputs.cache-hit != 'true'
        run: |
          if [ ! -d "${GITHUB_WORKSPACE}/plugins" ]; then
            mkdir plugins
          fi 
          
          tflint \
            --init \
            --config $(pwd)/.tflint.hcl

      - name: lint
        run: |
          tflint