name: Terraform Scan

# https://docs.github.com/en/actions/using-workflows/reusing-workflows#overview
on: workflow_call

jobs:        
  checkov:
    name: terraform checkov scan
    runs-on: ubuntu-latest
    env:
      CHECKOV_VERSION: 2.3.347
    steps:
      # see: https://github.com/actions/checkout
      - name: checkout
        uses: actions/checkout@v3
        
      # TODO: how to cache system dependencies?
      # see: https://github.com/cli/cli/issues/6175#issuecomment-1238477714
      - name: system dependencies
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          
          sudo apt-get update -y 
          sudo apt-get install -y \
                                  python3-dev \
                                  python3-venv \
                                  python3-pip \
                                  build-essential

      # see: https://github.com/actions/cache
      - name: cache
        id: cache_checkov
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/venv
          key: ${{ github.repository }}-checkov-${{ env.CHECKOV_VERSION }}-venv

      - name: job dependencies
        if: steps.cache_checkov.outputs.cache-hit != 'true'
        run: |
          python3 -m venv ${GITHUB_WORKSPACE}/venv
          source ${GITHUB_WORKSPACE}/venv/bin/activate
          pip3 install checkov==${CHECKOV_VERSION}

      # skip CKV2_GHA_1: "Ensure top-level permissions are not set to write-all"
      # because ignoring at the file level doesn't work...
      - name: scan
        run: |
          source ${GITHUB_WORKSPACE}/venv/bin/activate
          checkov --directory . \
            --download-external-modules True \
            --skip-path venv \
            --skip-check CKV2_GHA_1      

  tfsec:
    name: terraform security scan
    runs-on: ubuntu-latest
    env:
      TFSEC_VERSION: 1.28.1
    steps:
      # see: 
        # GITHUB_ENV: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
        # TFSEC_INSTALL_PATH: https://github.com/aquasecurity/tfsec/blob/da18cf5eeb62a9120dcae18aa034e63f2a934f40/scripts/install_linux.sh#L93
      - name: environment
        run: |
          echo "PATH=${GITHUB_WORKSPACE}/bin:$PATH" >> $GITHUB_ENV
        
      # https://github.com/actions/checkout
      - name: checkout
        uses: actions/checkout@v3

      # see: https://github.com/actions/cache
      - name: cache
        id: cache_tfsec
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/bin
          key: ${{ github.repository }}-${{ env.TFSEC_VERSION }}-tfsec

      - name: dependencies
        if: steps.cache_tfsec.outputs.cache-hit != 'true'
        run: |
          if [ ! -d "${GITHUB_WORKSPACE}/bin" ]; then
            mkdir ${GITHUB_WORKSPACE}/bin
          fi
          curl -L -o ${GITHUB_WORKSPACE}/bin/tfsec https://github.com/aquasecurity/tfsec/releases/download/v${TFSEC_VERSION}/tfsec-linux-amd64
          chmod +x ${GITHUB_WORKSPACE}/bin/tfsec

      # see: https://aquasecurity.github.io/tfsec/v1.27.6/guides/configuration/config/
      - name: scan
        run: |
          tfsec \
            --config-file .tfsec.yaml